### ISSUE TITLE
Error trying to use the check_docker.py remotely

### ISSUE THREAD

**Issue by Snoobz** [timdaman/check_docker#62]
Hello,

So here is the thing, I was trying to use the check_docker.py script using Python 3 on locally on the computer and it was working fine. I could see the output of the different containers that I was running, it was perfect. I have NRPE 2.15 installed on my computer and I want to use a remote computer that will send the checks and send the output on a monitoring screen (using Nagios).

The thing is, when a remote computer is using the check it doesn't work. Here is the command I type using Python 3 on the remote computer. 
python3 check_docker.py --connection 1.1.1.1:5666 --cpu 80:90

This command doesn't work. It shows me an error saying that the peer ended the connection. Of course I can ping both computers it's not a network related issue. I did a tcpdump on the computer that host the docker app, it receives the check from the 5666 port, so this is not a firewall issue.

The command: python3 check_docker.py  --cpu 80:90 works fine locally on the computer but when it comes to use it via the network, it doesn't work.

Any help is welcome.

EDIT: Here is the exact error returned by the Python 3 script.

Traceback (most recent call last):
  File "check_docker.py", line 1000, in main
    perform_checks(argv[1:])
  File "check_docker.py", line 955, in perform_checks
    containers = get_containers(args.containers, args.present)
  File "check_docker.py", line 332, in get_containers
    containers_list, _ = get_url(daemon + '/containers/json?all=1')
  File "check_docker.py", line 283, in get_url
    response = better_urllib_get.open(url, timeout=timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib64/python3.6/urllib/request.py", line 1321, in do_open
    r = h.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
UNKNOWN: Exception raised during check': ConnectionResetError(104, 'Connection reset by peer')

**Comment by Snoobz** [comment]
Problem solved... sorry for the bother.

The problem was that I didn't enable the Docker Remote REST API. After following this tutorial (for those interested) it solved my problem.

Link: http://www.littlebigextra.com/how-to-enable-remote-rest-api-on-docker-host/

PS: While doing this tutorial, I didn't have to put the = (between the H and the tcp) when typing the command in the service file.
-H=tcp://0.0.0.0:2375
